packages/jet-brains-integration/CHANGELOG.md, packages/jet-brains-integration/package.json, packages/solidjs-integration/CHANGELOG.md, packages/solidjs-integration/package.json, packages/solidjs-integration/src/type-generator.ts, packages/vs-code-integration/CHANGELOG.md, packages/vs-code-integration/package.json, packages/vs-code-integration/src/__tests__/cem-utilities.test.ts, tools/cem-utils/src/__tests__/cem-utilities.test.ts, tools/cem-utils/src/__tests__/description-templates.test.ts, tools/cem-utils/src/cem-utilities.ts, tools/cem-utils/src/description-templates.ts
- add deprecation descriptions for components
- prevent "undefined" strings in descriptions
=> Prevent undefined for descriptions

demo/lit-app/custom-elements-manifest.config.mjs, demo/lit-app/custom-elements.json, demo/lit-app/solid-js.d.ts, demo/lit-app/src/index.ts, demo/lit-app/src/radio-button/RadioButton.ts, demo/lit-app/src/radio-group/RadioGroup.ts, demo/lit-app/types/index.d.ts, demo/lit-app/types/radio-button/RadioButton.d.ts, demo/lit-app/types/radio-group/RadioGroup.d.ts, demo/solidjs-app/scoped-components.d.ts, packages/solidjs-integration/CHANGELOG.md, packages/solidjs-integration/README.md, packages/solidjs-integration/package.json, packages/solidjs-integration/src/type-generator.ts, tools/cem-utils/src/cem-utilities.ts
- include event types when importing components
- include docs on event typing best practices
=> Add solidjs event types

.github/workflows/ci.yaml, demo/solidjs-app/src/index.tsx
=> add github actions

packages/jet-brains-integration/CHANGELOG.md, packages/jet-brains-integration/README.md, packages/jet-brains-integration/package.json, packages/jet-brains-integration/src/types.d.ts, packages/jet-brains-integration/src/web-types-generator.ts, packages/solidjs-integration/CHANGELOG.md, packages/solidjs-integration/README.md, packages/solidjs-integration/package.json, packages/solidjs-integration/src/type-generator.ts, packages/solidjs-integration/src/types.d.ts, packages/vs-code-integration/CHANGELOG.md, packages/vs-code-integration/README.md, packages/vs-code-integration/package.json, packages/vs-code-integration/src/cem-utilities.ts, packages/vs-code-integration/src/data-file-generator.ts, packages/vs-code-integration/src/types.d.ts
- add scoping options with `prefix` and `suffix` options
=> Add scoping to builds

.github/workflows/ci.yaml, .vscode/settings.json, package.json, packages/jet-brains-integration/CHANGELOG.md, packages/jet-brains-integration/package.json, packages/jet-brains-integration/src/web-types-generator.ts, packages/solidjs-integration/CHANGELOG.md, packages/solidjs-integration/package.json, packages/solidjs-integration/src/cem-analyzer-plugin.ts, packages/solidjs-integration/src/type-generator.ts, packages/vs-code-integration/CHANGELOG.md, packages/vs-code-integration/package.json, packages/vs-code-integration/src/data-file-generator.ts, tools/integrations/src/files.ts
- add logs for output paths
- update CI to run analyzer with build
- exclude components without tag names from generation
=> Add logs for output paths

demo/lit-app/test.html, demo/lit-app/web-types.json, demo/vanilla-demo/web-types.json, packages/jet-brains-integration/CHANGELOG.md, packages/jet-brains-integration/README.md, packages/jet-brains-integration/package.json, packages/jet-brains-integration/src/cem-utilities.ts, packages/jet-brains-integration/src/types.d.ts, packages/jet-brains-integration/src/web-types-generator.ts
- Add slot details
- Add default values for attributes
- Fix `typeSrc` reference
=> Add slots to web types

demo/lit-app/custom-element-jsx.d.ts, demo/lit-app/custom-elements.json, demo/lit-app/solid-js.d.ts, demo/lit-app/src/radio-group/RadioGroup.ts, demo/lit-app/src/radio-group/types.d.ts, demo/lit-app/vscode.html-custom-data.json, demo/lit-app/web-types.json, demo/stencil-app/package.json, packages/expanded-types/CHANGELOG.md, packages/expanded-types/package.json, packages/expanded-types/src/cem-plugin.ts
- fixed imported types with file extensions
- fixed combined/extended union types
=> Fix Imported Types

packages/react-wrappers/CHANGELOG.md, packages/react-wrappers/package.json, packages/react-wrappers/src/global.ts
update type from `boolean` to `number | string`.
=> fix `key` prop type

packages/react-wrappers/CHANGELOG.md, packages/react-wrappers/package.json, packages/react-wrappers/src/utils.ts, packages/react-wrappers/src/wrapper-generator.ts
- Fix `Boolean` attribute rendering
- Fix duplicate `globalEvents`
- Fix duplicate `props`
=> add API patches

demo/lit-app/custom-elements.json, packages/react-wrappers/CHANGELOG.md, packages/react-wrappers/package.json, packages/react-wrappers/src/utils.ts, packages/react-wrappers/src/wrapper-generator.ts
- Fix exclude functionality
- Update event timing to bind before render
=> React wrappers event timing and exclude fintionality

demo/lit-app/custom-element-jsx.d.ts, demo/react-app/src/App.tsx, packages/jsx-integration/CHANGELOG.md, packages/jsx-integration/package.json, packages/jsx-integration/src/type-generator.ts, packages/react-wrappers/CHANGELOG.md, packages/react-wrappers/package.json, packages/react-wrappers/src/wrapper-generator.ts
- removed `prop:` prefix from JSX properties
- fixed React wrappers descriptions
=> Jsx-bug-fixes

packages/jet-brains-integration/CHANGELOG.md, packages/jet-brains-integration/README.md, packages/jet-brains-integration/package.json, packages/vuejs-integration/README.md, packages/vuejs-integration/package.json
- updated vuejs and jetbrains docs to reference the correct import paths and modules
=> update docs to reflect correct imports

packages/react-wrappers/src/utils.ts
useLayoutEffect was used but not imported
=> added useLayoutEffect

demo/lit-app/custom-element-jsx.d.ts, demo/lit-app/custom-element-vuejs.d.ts, demo/lit-app/custom-elements-manifest.config.mjs, demo/lit-app/custom-elements.json, demo/lit-app/solid-js.d.ts, demo/lit-app/src/radio-button/RadioButton.ts, demo/lit-app/vscode.html-custom-data.json, demo/lit-app/web-types.json, packages/react-wrappers/CHANGELOG.md, packages/react-wrappers/package.json, packages/react-wrappers/src/utils.ts, packages/react-wrappers/src/wrapper-generator.ts
- Fixed attribute mapping error (#44)
- Updated attribute binding to execute before render (#34)
=> React wrappers attribute mapping

demo/lit-app/custom-element-jsx.d.ts, demo/lit-app/custom-element-vuejs.d.ts, demo/lit-app/custom-elements.json, demo/lit-app/solid-js.d.ts, demo/lit-app/src/radio-button/RadioButton.ts, demo/lit-app/src/radio-group/RadioGroup.ts, demo/lit-app/vscode.html-custom-data.json, demo/lit-app/web-types.json, packages/expanded-types/CHANGELOG.md, packages/expanded-types/package.json, packages/expanded-types/src/cem-plugin.ts, packages/vs-code-integration/src/__tests__/cem-utilities.test.ts, packages/vs-code-integration/src/__tests__/test-data.ts
- Fixed module paths that were preventing inheritance
- Small performance improvement
=> Expanded types fix module path

demo/lit-app/custom-elements.json, demo/lit-app/src/radio-group/RadioGroup.ts, demo/lit-app/tsconfig.json, packages/jet-brains-integration/CHANGELOG.md, packages/jet-brains-integration/package.json, packages/jsx-integration/CHANGELOG.md, packages/jsx-integration/package.json, packages/react-wrappers/CHANGELOG.md, packages/react-wrappers/src/global.ts, packages/react-wrappers/src/utils.ts, packages/react-wrappers/src/wrapper-generator.ts, packages/solidjs-integration/CHANGELOG.md, packages/solidjs-integration/package.json, packages/vs-code-integration/CHANGELOG.md, packages/vs-code-integration/package.json, packages/vuejs-integration/CHANGELOG.md, packages/vuejs-integration/package.json, tools/cem-utils/src/cem-utilities.ts
- Exclude private members using the `#` access modifier
- Add `htmlFor` global prop
- Patched issue with `className` prop
- Patched issue with `style` prop when using style object
- Removed redundant prop listing
- Removed attribute utility helpers
=> Optimize React Wrappers

demo/lit-app/custom-element-jsx.d.ts, demo/stencil-app/tsconfig.json, package-lock.json, packages/jsx-integration/CHANGELOG.md, packages/jsx-integration/README.md, packages/jsx-integration/package.json, packages/jsx-integration/src/type-generator.ts, packages/jsx-integration/src/types.d.ts, packages/react-wrappers/CHANGELOG.md, packages/react-wrappers/README.md, packages/react-wrappers/package.json, packages/react-wrappers/src/types.d.ts, packages/react-wrappers/src/wrapper-generator.ts, packages/solidjs-integration/CHANGELOG.md, packages/solidjs-integration/README.md, packages/solidjs-integration/package.json, packages/solidjs-integration/src/type-generator.ts, packages/solidjs-integration/src/types.d.ts, packages/vuejs-integration/CHANGELOG.md, packages/vuejs-integration/README.md, packages/vuejs-integration/package.json, packages/vuejs-integration/src/type-generator.ts, packages/vuejs-integration/src/types.d.ts
Added a resolver for packages that do not provide named exports. This change includes:
- JSX Types
- React wrappers
- SolidJS Types
- Vuejs Types
=> add default export resolver

demo/lit-app/custom-element-jsx.d.ts, demo/lit-app/custom-elements.json, demo/lit-app/vscode.html-custom-data.json, demo/lit-app/web-types.json, packages/expanded-types/CHANGELOG.md, packages/expanded-types/package.json, packages/expanded-types/src/cem-plugin.ts
This PR should resolve the additional issues noted in #18.
=> resolve external tpes in union types

demo/lit-app/custom-element-jsx.d.ts, demo/lit-app/custom-elements.json, demo/lit-app/solid-js.d.ts, packages/jsx-integration/CHANGELOG.md, packages/jsx-integration/package.json, packages/jsx-integration/src/type-generator.ts, packages/react-wrappers/CHANGELOG.md, packages/react-wrappers/package.json, packages/react-wrappers/src/global.ts, packages/react-wrappers/src/types.d.ts, packages/react-wrappers/src/utils.ts, packages/react-wrappers/src/wrapper-generator.ts, packages/solidjs-integration/CHANGELOG.md, packages/solidjs-integration/package.json, packages/solidjs-integration/src/type-generator.ts
- Added additional default attributes - `className`, `dir`, `exportparts`, `htmlFor`, `hidden`, `id`, `lang`, `ref`, `tabIndex`, `title`, and `translate`.
- Added additional default attributes - `classList`, `dir`, `exportparts`, `id`, `lang`, `part`, `title`, and `translate`
- Fixed attribute mapping in types
- Added additional default attributes - `dir`, `exportparts`, `htmlFor`, `hidden`, `id`, `lang`, `ref`, `tabIndex`, `title`, and `translate`.
=> Add Addtional Attributes for JSX Projects

demo/lit-app/custom-elements-manifest.config.mjs, demo/lit-app/package.json, demo/react-app/src/App.tsx, package-lock.json, packages/react-wrappers/CHANGELOG.md, packages/react-wrappers/README.md, packages/react-wrappers/src/global.ts, packages/react-wrappers/src/types.d.ts, packages/react-wrappers/src/wrapper-generator.ts
=> make react types extendable

packages/jsx-integration/CHANGELOG.md, packages/jsx-integration/package.json, packages/jsx-integration/src/type-generator.ts
fix https://github.com/break-stuff/cem-tools/issues/109
=> Export props type

demo/lit-app/custom-element-jsx.d.ts, packages/jsx-integration/CHANGELOG.md, packages/jsx-integration/README.md, packages/jsx-integration/package.json, packages/jsx-integration/src/type-generator.ts
- Added `class` prop back into types
- Added link to sandbox to README
=> Add class to jsx types

demo/lit-app/custom-element-jsx.d.ts, demo/lit-app/custom-elements-manifest.config.mjs, demo/react-app/src/App.tsx, packages/react-wrappers/CHANGELOG.md, packages/react-wrappers/README.md, packages/react-wrappers/src/types.d.ts, packages/react-wrappers/src/utils.ts, packages/react-wrappers/src/wrapper-generator.ts
Adds context provider to provide runtime scoping for custom element tag names.
Closes #119
=> add component tag name scoping

packages/react-wrappers/CHANGELOG.md, packages/react-wrappers/package.json, packages/react-wrappers/src/wrapper-generator.ts
=> fix issue with unused props

demo/lit-app/custom-elements.json, packages/custom-jsdoc-tags/CHANGELOG.md, packages/custom-jsdoc-tags/package.json, packages/custom-jsdoc-tags/src/cem-plugin.ts, packages/expanded-types/CHANGELOG.md, packages/expanded-types/package.json, packages/expanded-types/src/cem-plugin.ts
=> fixed issue with "path" import

demo/lit-app/custom-element-jsx.d.ts, packages/jsx-integration/CHANGELOG.md, packages/jsx-integration/package.json, packages/jsx-integration/src/type-generator.ts
=> fix JSX event names

.prettierrc.mjs, demo/lit-app/custom-element-jsx.d.ts, demo/lit-app/custom-element-vuejs.d.ts, demo/lit-app/custom-elements-svelte.d.ts, demo/lit-app/loader.js, demo/lit-app/solid-js.d.ts, packages/react-wrappers/src/wrapper-generator.ts, packages/vuejs-integration/CHANGELOG.md, packages/vuejs-integration/README.md, packages/vuejs-integration/package.json, packages/vuejs-integration/src/type-generator.ts, packages/vuejs-integration/src/types.d.ts
=> Vue add prefix and suffix

demo/lit-app/solid-js.d.ts, packages/solidjs-integration/CHANGELOG.md, packages/solidjs-integration/package.json, packages/solidjs-integration/src/type-generator.ts
=> add directive support for Solidjs types

demo/lit-app/build.js, demo/lit-app/package.json, demo/lit-app/vscode.html-custom-data.json, demo/lit-app/web-types.json, packages/jet-brains-integration/CHANGELOG.md, packages/jet-brains-integration/README.md, packages/jet-brains-integration/package.json, packages/jet-brains-integration/src/index.ts, packages/jet-brains-integration/src/web-types-generator.ts, packages/vs-code-integration/CHANGELOG.md, packages/vs-code-integration/README.md, packages/vs-code-integration/package.json, packages/vs-code-integration/src/data-file-generator.ts, packages/vs-code-integration/src/index.ts
Add the ability to generate JetBrains and VS Code editor data file contents programmatically.
Resolves #142
=> add ability to programmatically generate file contents

packages/jet-brains-integration/CHANGELOG.md, packages/jet-brains-integration/package.json, packages/jet-brains-integration/src/web-types-generator.ts
=> fix `referenceTemplate` mapping

demo/lit-app/custom-elements.json, packages/custom-jsdoc-tags/CHANGELOG.md, packages/custom-jsdoc-tags/package.json, packages/custom-jsdoc-tags/src/cem-plugin.ts, packages/eslint-rules/CHANGELOG.md, packages/eslint-rules/package.json, packages/expanded-types/CHANGELOG.md, packages/expanded-types/package.json, packages/expanded-types/src/cem-plugin.ts, packages/jet-brains-integration/CHANGELOG.md, packages/jet-brains-integration/package.json, packages/jsx-integration/CHANGELOG.md, packages/jsx-integration/package.json, packages/lazy-loader/CHANGELOG.md, packages/lazy-loader/package.json, packages/react-wrappers/CHANGELOG.md, packages/react-wrappers/package.json, packages/solidjs-integration/CHANGELOG.md, packages/solidjs-integration/package.json, packages/svelte-integration/CHANGELOG.md, packages/svelte-integration/package.json, packages/vs-code-integration/CHANGELOG.md, packages/vs-code-integration/package.json, packages/vuejs-integration/CHANGELOG.md, packages/vuejs-integration/package.json, pnpm-lock.yaml, tools/integrations/package.json, tools/integrations/src/files.ts
=> fix async file generation
